### ISSUE TITLE
Nemůžu deploynout ulohu: Cannot update the ref 'refs/remotes/origin/master': unable to append to .git/logs/refs/remotes/origin/master: Permission denied

### ISSUE THREAD

**Issue by jiridanek** [fi-ksi/web-backend#127]
```
Fetching origin...
Exception: Traceback (most recent call last):
  File "/root/web-backend/util/admin/taskDeploy.py", line 69, in deploy
    for fetch_info in repo.remotes.origin.fetch():
  File "/root/web-backend/ksi-py3-venv/lib/python3.7/site-packages/git/remote.py", line 797, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/root/web-backend/ksi-py3-venv/lib/python3.7/site-packages/git/remote.py", line 676, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/root/web-backend/ksi-py3-venv/lib/python3.7/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v origin
  stderr: 'error: Cannot update the ref 'refs/remotes/origin/master': unable to append to .git/logs/refs/remotes/origin/master: Permission denied
From github.com-ksi:fi-ksi/seminar
 ! ad5e91f..e3eb94a  master     -> origin/master  (unable to update local ref)
 = [up to date]      2019_03_xx_testovani -> origin/2019_03_xx_testovani
 = [up to date]      2019_04_xx_staticky_typovany_python -> origin/2019_04_xx_staticky_typovany_python
 = [up to date]      2020_02_14_velka_castecna_aplikace -> origin/2020_02_14_velka_castecna_aplikace
 = [up to date]      2020_03_01_typovani_a_mypy -> origin/2020_03_01_typovani_a_mypy
 = [up to date]      2020_03_02_zaklady_testovani -> origin/2020_03_02_zaklady_testovani
 = [up to date]      2020_03_03_ledoborec -> origin/2020_03_03_ledoborec
 = [up to date]      2020_03_04_dekoratory -> origin/2020_03_04_dekoratory
 = [up to date]      2020_03_05_asserty -> origin/2020_03_05_asserty
 = [up to date]      2020_03_06_bruteforce_a_itertools -> origin/2020_03_06_bruteforce_a_itertools
 = [up to date]      2020_03_07_hypothesis -> origin/2020_03_07_hypothesis
error: Cannot update the ref 'refs/remotes/origin/2020_03_08_pytest': unable to append to .git/logs/refs/remotes/origin/2020_03_08_pytest: Permission denied
 ! 1b550fc..c7fc341  2020_03_08_pytest -> origin/2020_03_08_pytest  (unable to update local ref)
 = [up to date]      2020_03_09_dalsi_typy_testu -> origin/2020_03_09_dalsi_typy_testu
 = [up to date]      2020_03_10_git_basics -> origin/2020_03_10_git_basics
 = [up to date]      2020_03_11_velka_hypothesis -> origin/2020_03_11_velka_hypothesis
 = [up to date]      2020_03_12_github_ci_cd -> origin/2020_03_12_github_ci_cd
 = [up to date]      2020_03_13_karlik_a_turinguv_test -> origin/2020_03_13_karlik_a_turinguv_test
 = [up to date]      2020_03_14_bruteforce_teoreticky -> origin/2020_03_14_bruteforce_teoreticky
 = [up to date]      outdoor_uloha_fotky -> origin/outdoor_uloha_fotky'

Done
```

**Comment by horacekj** [comment]
Moje chyba. Dělal jsem nějaké operace ručně a neopravil jsem oprávnění. Opraveno.
